// qn-demo/src/pages/index/index.tsx
import { Component, PropsWithChildren } from "react";
import { View, Table, TableColumn } from "@tarojs/components";
import "./index.less";

export default class Index extends Component<PropsWithChildren> {
  state = {
    dataSource: (() => {
      const result = [] as any[];
      for (let i = 0; i < 5; i++) {
        result.push({
          id: 100306660940 + i,
          time: 2000 + i,
        });
      }
      return result;
    })(),
  };

  componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  render() {
    const { dataSource } = this.state;
    return (
      <View>
        <Table dataSource={dataSource}>
          <TableColumn title="Id" dataIndex="id" />
          <TableColumn title="Time" dataIndex="time" />
        </Table>
      </View>
    );
  }
}

// ci-demo/src/pages/index/index.vue
<template>
  <view>
    <table :dataSource="dataSource">
      <table-column title="Id" dataIndex="id" />
      <table-column title="Time" dataIndex="time" />
    </table>
  </view>
</template>

<script setup>
import { computed } from 'vue'
import { Table, TableColumn } from '@tarojs/components'
import './index.less'

const dataSource = computed(() => {
  const result = []
  for (let i = 0; i < 5; i++) {
    result.push({
      title: {
        name: `Quotation for 1PCS Nano ${3 + i}.0 controller compatible`
      },
      id: 100306660940 + i,
      time: 2000 + i
    })
  }
  return result
})

</script>
